version: '3.8'

services:
  app:
    build: .
    container_name: backend-sensorcensor
    restart: unless-stopped
    networks:
      default:
        external:
          name: devops_shared
    env_file:
      - .env
