version: '3.8'

services:
  app:
    build: .
    container_name: backend-sensorcensor
    restart: unless-stopped
    networks:
      - devops_shared
    env_file:
      - .env

networks:
  devops_shared:
    external: true
